apps/accounts/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView


app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('apps.main.urls', namespace='main')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    path('product/', include('apps.product.urls', namespace='product')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager
import datetime
from django.urls import reverse
from django.utils.html import mark_safe


class User(AbstractBaseUser, PermissionsMixin):
    profile_img = models.ImageField(null=True, blank=True, verbose_name='تصویر پروفایل')
    phone_number = models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')
    first_name = models.CharField(max_length=50, verbose_name='نام')
    last_name = models.CharField(max_length=50, verbose_name='نام خانوادگی')
    date_of_birth = models.DateField(verbose_name='تاریخ تولد', null=True, blank=True)
    email = models.EmailField(max_length=255, unique=True, verbose_name='ایمیل', null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name='فعال', help_text='بعد از وارد کردن کد ارسالی فعال میشود')
    is_admin = models.BooleanField(default=False, verbose_name='ادمین')   
    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def age(self):
        age = datetime.date.today() - self.date_of_birth
        return age

    def is_staff(self):
        return self.is_admin

    def min_profile_img(self):
        return mark_safe('<img src="/media/%s" height="50" />' % (self.profile_img))
        
    min_profile_img.short_description = 'تصویر'
    age.short_description = 'سن'
    is_staff.short_description = 'اجازه ورود به پنل امین'
    

    def __str__(self):
        return f'{self.first_name} {self.last_name} - ادمین: {self.is_admin}'

    class Meta:
        verbose_name = 'کاربر'
        verbose_name_plural = 'کاربرها'
        

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='addresses', verbose_name='کاربر')
    receiver_name = models.CharField(max_length=60, verbose_name='نام دریافت کننده', null=True)
    receiver_phone_number = models.CharField(max_length=11, verbose_name='شماره تلفن دریافت کننده', null=True)
    state = models.CharField(max_length=20, verbose_name='استان', null=True)
    city = models.CharField(max_length=20, verbose_name='شهر', null=True)
    postal_code = models.CharField(max_length=20, verbose_name='کد پستی', null=True)
    address = models.TextField(max_length=455, verbose_name='آدرس', blank=True, null=True)

    def __str__(self):
        return self.city

    def __iter__(self):
        address = self.__dict__
        for item in address.items():
            yield item

    def get_absolute_url(self):
        return reverse('dashboard:edit_address', args=(self.id,))

    class Meta:
        verbose_name = 'آدرس'
        verbose_name_plural = 'آدرس ها'


class OTPCode(models.Model):
    user = models.ForeignKey(User, related_name='otp_codes', on_delete=models.CASCADE, verbose_name='کاربر')
    code = models.CharField(max_length=6, verbose_name='کد')
    valid_to = models.DateTimeField(null=True, verbose_name='معتبر تا')

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = 'کد یکبار مصرف'
        verbose_name_plural = 'کدهای یکبار مصرف'

apps/accounts/forms.py
from django import forms
from .models import User, OTPCode
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.urls import reverse


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='رمزعبور', widget=forms.PasswordInput)
    password2 = forms.CharField(label='تکرار رمزعبور', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('profile_img', 'first_name', 'last_name', 'phone_number', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('passwords dont match')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(
        help_text="you can change password using <a href=\"../password/\">this form</a>.", label='رمزعبور')

    class Meta:
        model = User
        fields = ('profile_img', 'first_name', 'last_name', 'phone_number', 'email', 'password', 'last_login')


class VerifyCodeForm(forms.Form):
    code = forms.IntegerField()


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone_number', 'password']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise ValidationError('رمز عبور و تایید رمز عبور یکسان نیست')
        return confirm_password

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')

        if User.objects.filter(phone_number=phone_number).exists():
            raise ValidationError('شماره تلفن قبلا ثبت نام کرده')
        return phone_number


class LoginForm(forms.Form):
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if User.objects.filter(phone_number=phone_number).exists():
            return phone_number
        register_page = reverse('accounts:register')
        raise ValidationError(f'حسابی با شماره تلفن مورد نظر موجود نیست،'
                              f' <a href="{register_page}">ساخت حساب کاربری</a>')

apps/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from .forms import RegisterForm, LoginForm
from .models import User
from django.contrib.auth import authenticate, login, logout


class RegisterView(View):
    template_name = 'accounts/register.html'
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.warning(request, 'برای ساخت حساب جدید ابتدا از حساب خود خارج شوید', 'warning')
            return redirect('dashboard:dashboard')
        return super().dispatch(request, request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        # if user data were correct
        if form.is_valid():
            cleaned_data = form.cleaned_data
            # create user instance
            User.objects.create_user(
                first_name=cleaned_data['first_name'],
                last_name=cleaned_data['last_name'],
                phone_number=cleaned_data['phone_number'],
                password=cleaned_data['password']
            )
            messages.success(request, 'حساب شما با موفقیت ساخته شد', 'success')
            # return redirect('accounts:login')
        messages.error(request, 'مشکلی در ساخت حساب شما به وجود آمد، لطفا دوباره تلاش کنید', 'danger')
        return render(request, self.template_name, {'form': form})


class LoginView(View):
    template_name = 'accounts/login.html'
    form_class = LoginForm

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.warning(request, 'قبلا وارد حساب خود شده اید', 'warning')
            return redirect('dashboard:dashboard')
        return super().dispatch(request, request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user = authenticate(phone_number=cleaned_data['phone_number'],password=cleaned_data['password'])
            if user:
                login(request, user)
                messages.success(request, 'با موفقیت وارد حسابتان شدید', 'success')
                if self.next:
                    return redirect(self.next)
                return redirect('dashboard:dashboard')
            messages.error(request, 'اطلاعات کاربری صحیح نیست', 'danger')
            return render(request, self.template_name, {'form': form})
        messages.error(request, 'اطلاعات ورود را به درستی وارد کنید', 'danger')
        return render(request, self.template_name, {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.info(request, 'از حساب خود خارج شدید', 'info')
        return redirect('accounts:login')

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="../../../../Downloads/DarsmanShopTemplate/index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="#">حساب کاربری</a>
									/
								</li>
								<li class="active" aria-current="page">ورود به حساب کاربری</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>ورود به حساب کاربری</h1>
					</div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6">
							<div class="card flex-grow-1 mb-md-0">
								<div class="card-body">
									<h3 class="card-title">ورود</h3>
									<form method="post">
										{% csrf_token %}
										<div class="form-group">
											<label for="id_phone_number">شماره همراه</label>
											{{ form.phone_number }}
											{{ form.phone_number.errors.0|safe }}
										</div>
										<div class="form-group">
											<label for="id_password">رمز عبور</label>
											{{ form.password }}
											{{ form.password.errors.0 }}
											<small class="form-text text-muted"><a href="">فراموشی رمز عبور</a></small>
										</div>
										<div class="form-group">
											<div class="form-check"><span class="form-check-input input-check"><span class="input-check__body"><input class="input-check__input" type="checkbox" id="login-remember"> <span class="input-check__box"></span>
												<svg class="input-check__icon" width="9px" height="7px">
													<use xlink:href="images/sprite.svg#check-9x7"></use>
												</svg>
												</span>
												</span>
												<label class="form-check-label" for="login-remember">به خاطر سپاری</label>
											</div>
										</div>
										<button type="submit" class="btn btn-primary mt-4">ورود</button>
									</form>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="">حساب کاربری</a>
									/
								</li>
								<li class="active" aria-current="page"> ایجاد حساب کاربری</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>ایجاد حساب کاربری جدید</h1></div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6 d-flex mt-4 mt-md-0">
							<div class="card flex-grow-1 mb-0">
								<div class="card-body">
									<h3 class="card-title">ثبت نام</h3>
									<form method="post">
										{% csrf_token %}
										<div class="form-group">
											<label for="id_first_name">نام</label>
											{{ form.first_name}}
											<p class="text-danger">{{ form.errors.first_name.0 }}</p>
										</div>
										<div class="form-group">
											<label for="id_last_name">نام خانوادگی</label>
											{{ form.last_name }}
											<p class="text-danger">{{ form.errors.last_name.0 }}</p>
										</div>
										<div class="form-group">
											<label for="id_phone_number">تلفن همراه</label>
											{{ form.phone_number }}
											<p class="text-danger">{{ form.errors.phone_number.0 }}</p>
										</div>
										<div class="form-group">
											<label for="id_password">رمز عبور</label>
											{{ form.password }}
											<p class="text-danger">{{ form.errors.password.0 }}</p>
										</div>
										<div class="form-group">
											<label for="id_confirm_password">تایید رمز عبور</label>
											{{ form.confirm_password }}
											<p class="text-danger">{{ form.errors.confirm_password.0 }}</p>
										</div>
										<button type="submit" class="btn btn-primary mt-4">ثبت نام</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->
{% endblock %}