admin_soft/urls.py
from django.urls import path
from admin_soft import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.index, name='index'),
    path('billing/', views.billing, name='billing'),
    path('tables/', views.tables, name='tables'),
    path('vr/', views.vr, name='vr'),
    path('rtl/', views.rtl, name='rtl'),
    path('profile/', views.profile, name='profile'),

    # Authentication
    path('accounts/login/', views.UserLoginView.as_view(), name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'
    ), name="password_change_done"),
    path('accounts/password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', 
        views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),
]

apps/blog/urls.py
from django.urls import path
from .views import BlogView, PostView, LatestPostsPartial


app_name = 'blog'
urlpatterns = [
    path('', BlogView.as_view(), name='blog'),
    path('post/<int:id>/<slug:slug>/', PostView.as_view(), name='post'),
    path('latest-posts/', LatestPostsPartial.as_view(), name='latest_posts'),
]

apps/cart/urls.py
from django.urls import path


app_name = 'cart'
urlpatterns = [
    # path()
]

apps/main/urls.py
from django.urls import path
from .views import (HomeView,
                    ProductSpecialOffersPartial, 
                    BestSellersProductPartial, 
                    PopularCategories,
                    NewestProductsPartial,
                    SliderPartialView,
                    BrandPartialView)


app_name = 'main'
urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('special-offer-products/',ProductSpecialOffersPartial.as_view(), name='product_special_offer_partial'),
    path('best-sellers-products/',BestSellersProductPartial.as_view(), name='best_sellers_product_partial'),
    path('popular-categories/',PopularCategories.as_view(), name='popular_categories_partial'),
    path('newset-products/',NewestProductsPartial.as_view(), name='newset_product_partial'),
    path('slider-partial/', SliderPartialView.as_view(), name='slider_partial'),
    path('brand-partial/', BrandPartialView.as_view(), name='brand_partial'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('apps.main.urls', namespace='main')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    path('product/', include('apps.product.urls', namespace='product')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
<!-- site__footer -->
<footer class="site__footer">
    <div class="site-footer">
        <div class="container">
            <div class="site-footer__widgets">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="site-footer__widget footer-contacts">
                            <h5 class="footer-contacts__title">تماس با ما</h5>

                            <ul class="footer-contacts__contacts">
                                <li><i class="footer-contacts__icon fas fa-globe-americas"></i>
                                    کرج، میدان شهدا</li>
                                <li><i class="footer-contacts__icon fas fa-mobile-alt"></i>
                                    <span class="ltr_text">09201502830</span>
                                </li>

                            </ul>
                        </div>
                    </div>
                    <div class="col-6 col-md-3 col-lg-2">
                        <div class="site-footer__widget footer-links">
                            <h5 class="footer-links__title">اطلاعات</h5>
                            <ul class="footer-links__list">
                                <li class="footer-links__item">
                                    <a href="" class="footer-links__link">تماس با ما</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-6 col-md-3 col-lg-2">
                        <div class="site-footer__widget footer-links">
                            <h5 class="footer-links__title">حساب کاربری</h5>
                            <ul class="footer-links__list">
                                <li class="footer-links__item">
                                    <a href="{% url 'accounts:login' %}" class="footer-links__link">
                                        ورود
                                    </a>
                                </li>
                                <li class="footer-links__item">
                                    <a href="{% url 'accounts:register' %}" class="footer-links__link">
                                        ثبت نام
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-12 col-md-12 col-lg-4">
                        <div class="site-footer__widget footer-newsletter">
                            <h5 class="footer-contacts__title">شبکه های</h5>
                            <div class="footer-newsletter__text footer-newsletter__text--social">ما را در شبکه
                                های اجتماعی دنبال کنید</div>
                            <ul class="footer-newsletter__social-links">
                                <li
                                    class="footer-newsletter__social-link footer-newsletter__social-link--instagram">
                                    <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="site-footer__bottom">

                <div class="site-footer__copyright">
                    کلیه حقوق و امتیازات این وبسایت متعلق است به فروشگاه
                    <a href="{{ request.build_absolute_uri }}" target="_blank">جِی‌مُد</a>
                </div>

            </div>
        </div>
    </div>
</footer>
<!-- site__footer / end -->

templates/includes/head.html
{% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="format-detection" content="telephone=no">
   <link rel="icon" type="image/png" href="{{ MEDIA_URL }}images/favicon.png">
    <!-- css -->
	<link rel="stylesheet" href="{% static 'vendor/bootstrap-4.5.3/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel-2.3.4/assets/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<!-- js -->
	<script src="{% static 'vendor/jquery-3.3.1/jquery.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap-4.5.3/js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendor/owl-carousel-2.3.4/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	<!-- font - fontawesome -->
 <link rel="stylesheet" href="{% static 'vendor/fontawesome-5.6.3/css/all.min.css' %}">
{#	<link rel="stylesheet" href="{% static 'vendor/FontAwesome.Pro.6.1.2-Web/css/all.min.css' %}">#}

templates/includes/latest_posts.html
{% load jalali_tags %}


 
{% comment %} {% load i18 %}    {% endcomment %}
{% if latest_posts %}
<div class="block block-posts block-posts--layout--grid-nl" data-layout="grid-nl">
    <div class="container">
        <div class="block-header">
            <h3 class="block-header__title">آخرین مقالات</h3>
            <div class="block-header__divider"></div>
            <div class="block-header__arrows-list">

                <button class="block-header__arrow block-header__arrow--left" type="button">
                    <i class="fas fa-angle-right"></i>
                </button>
                <button class="block-header__arrow block-header__arrow--right" type="button">
                    <i class="fas fa-angle-left"></i>
                </button>
            </div>
        </div>
        <div class="block-posts__slider">
            <div class="owl-carousel">
            {% for post in latest_posts %}   
            <div class="post-card">
                <div class="post-card__image post-image">
                    <a href="">
                        <img src="{{ MEDIA_URL }}{{ post.cover_img }}" alt="">
                    </a>
                </div>
                <div class="post-card__info">
                    <div class="post-card__category"><a href="">پیشنهادهای ویژه</a></div>
                    <div class="post-card__name">
                        <a href="">{{ post.title }}</a>
                    </div>
                    {% with time=post.publish_date|to_jalali:'%A %d %B %Y' %}
                    <div class="post-card__date">{{ time }}</div>
                    {% endwith %}
                    {% if post.short_description %}
                    <div class="post-card__content">{{ post.short_description }}</div>
                    {% endif %}
                    <div class="post-card__read-more"><a href="{{ post.get_absolute_url}}" class="btn btn-secondary btn-sm">بیشتر
                            بخوانید</a></div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endif %}

templates/includes/messages.html
{% for message in messages %}
    {% if message %}
        <p class="alert alert-{{ message.tags }} m-0 py-2 text-center">{{ message }}</p>
    {% endif %}
{% endfor %}
<p id="popup-message" class="alert alert-success w-100 text-center text-white m-0 p-0"></p>

templates/includes/navbar.html
{% load static %}
<!-- mobilemenu -->
	<div class="mobilemenu">
		<div class="mobilemenu__backdrop"></div>
		<div class="mobilemenu__body">
			<div class="mobilemenu__header">
				<div class="mobilemenu__title">منو</div>
				<button type="button" class="mobilemenu__close">
					<i class="fa fa-bars"></i>
				</button>
			</div>
			<div class="mobilemenu__content">
				<ul class="mobile-links mobile-links--level--0" data-collapse
					data-collapse-opened-class="mobile-links__item--open">
					<li class="mobile-links__item" data-collapse-item>
						<div class="mobile-links__item-title">
							<a href="{% url 'main:home' %}" class="mobile-links__item-link">خانه</a>
							<button class="mobile-links__item-toggle" type="button" data-collapse-trigger>
								<i class="fa fa-home"></i>
							</button>
						</div>
					</li>
					<li class="mobile-links__item" data-collapse-item>
						<div class="mobile-links__item-title"><a href="{% url 'product:category' None %}" class="mobile-links__item-link">دسته ها</a>
							<button class="mobile-links__item-toggle" type="button" data-collapse-trigger>
								<i class="fa fa-list"></i>
							</button>
						</div>
						<div class="mobile-links__item-sub-links" data-collapse-content>
							<ul class="mobile-links mobile-links--level--1">
								{% for category in navbar_categories %}
									{% if not category.parent %}
									<li class="mobile-links__item" data-collapse-item>
										<div class="mobile-links__item-title">

										<a href="{{ category.get_absolute_url }}" class="mobile-links__item-link">{{ category.title }}</a>

										{% if category.children.all %}
											<button class="mobile-links__item-toggle" type="button" data-collapse-trigger>
												<i class="fa fa-angle-double-down"></i>
											</button>
										{% endif %}
										</div>
										{% if category.children.all %}
											<div class="mobile-links__item-sub-links" data-collapse-content>
												<ul class="mobile-links mobile-links--level--2">
													{% for child in category.children.all %}
														<li class="mobile-links__item" data-collapse-item>
															<div class="mobile-links__item-title">
																	<a href="{{ child.get_absolute_url }}" class="mobile-links__item-link">{{ child.title }}</a>
															</div>
														</li>
													{% endfor %}
												</ul>
											</div>
										{% endif %}

									</li>
									{% endif %}
								{% endfor %}
							</ul>
						</div>
					</li>

					<li class="mobile-links__item" data-collapse-item>
						<div class="mobile-links__item-title">
							<a href="{% url 'dashboard:dashboard' %}" class="mobile-links__item-link">حساب
								کاربری
							</a>
							<button class="mobile-links__item-toggle" type="button" data-collapse-trigger>
								<i class="fa fa-user"></i>
							</button>
						</div>
						<div class="mobile-links__item-sub-links" data-collapse-content>
							<ul class="mobile-links mobile-links--level--1">
								<li class="mobile-links__item" data-collapse-item>
									<div class="mobile-links__item-title">
										<a href="{% url 'accounts:login' %}" class="mobile-links__item-link">ورود</a>
									</div>
								</li>
								<li class="mobile-links__item" data-collapse-item>
									<div class="mobile-links__item-title">
										<a href="{% url 'accounts:register' %}" class="mobile-links__item-link">ثبت نام</a>
									</div>
								</li>

							</ul>
						</div>
					</li>
					<li class="mobile-links__item" data-collapse-item>
						<div class="mobile-links__item-title">
							<a href="{% url 'blog:blog' %}" class="mobile-links__item-link">بلاگ</a>
							<button class="mobile-links__item-toggle" type="button" data-collapse-trigger>
								<i class="fa fa-newspaper"></i>
							</button>
						</div>
					</li>

				</ul>
			</div>
		</div>
	</div>
	<!-- mobilemenu / end -->
	<!-- site -->

	<div class="site">

		<!-- mobile site__header -->
		<header class="site__header d-lg-none">
			<div class="mobile-header mobile-header--sticky mobile-header--stuck">
				<div class="mobile-header__panel">
					<div class="container">
						<div class="mobile-header__body">
							<button class="mobile-header__menu-button">
								<i class="fa fa-bars "></i>
							</button>
							<a class="mobile-header__logo" href="index.html">
								<img src="images/logo.png" alt="">
							</a>
							<div class="mobile-header__search">
								<form class="mobile-header__search-form" action="">
									<input class="mobile-header__search-input" name="search"
										placeholder="جستجو از میان 10,000 محصول" aria-label="Site search" type="text"
										autocomplete="off">
									<button class="mobile-header__search-button mobile-header__search-button--submit"
										type="submit">
										<i class="fa fa-search"></i>
									</button>
									<button class="mobile-header__search-button mobile-header__search-button--close"
										type="button">
										<i class="fa fa-times"></i>
									</button>
									<div class="mobile-header__search-body"></div>
								</form>
							</div>
							<div class="mobile-header__indicators">
								<div class="indicator indicator--mobile-search indicator--mobile d-sm-none">
									<button class="indicator__button"><span class="indicator__area">
											<i class="fa fa-search"></i>
										</span></button>
								</div>
								<div class="indicator indicator--mobile d-sm-flex d-none">
									<a href="wishlist.html"	class="indicator__button">
										<span class="indicator__area">
											<i class="fa fa-heart"></i>
											<span class="indicator__value">0</span>
										</span>
									</a>
								</div>
								<div class="indicator indicator--mobile d-sm-flex d-none">
									<a href="wishlist.html"	class="indicator__button">
										<span class="indicator__area">
											<i class="fa fa-heart"></i>
											<span class="indicator__value">0</span>
										</span>
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>
		<!-- mobile site__header / end -->

		<!-- desktop site__header -->
		<header class="site__header d-lg-block d-none">
			<div class="site-header">

				<!-- .topbar -->
				<div class="site-header__topbar topbar">
					<div class="topbar__container container">
						<div class="topbar__row">
							{% comment %} <div class="topbar__item topbar__item--link"><a class="topbar-link"
									href="../about-us.html">درباره ما</a>
							</div>
							<div class="topbar__item topbar__item--link"><a class="topbar-link"
									href="../contact-us.html">تماس با ما</a>
							</div> {% endcomment %}

							<div class="topbar__spring"></div>
							<div class="topbar__item">
								<div class="topbar-dropdown">
									<button class="topbar-dropdown__btn" type="button">
										<a href="{% url 'dashboard:dashboard' %}" class="topbar-link">
											<i class="fa fa-user"></i>
											{% if request.user.is_authenticated %}
											{{ request.user.first_name }}&nbsp;خوش آمدید
											{% else %}
											پنل کاربری
											{% endif %}
										</a>

									</button>
								</div>
							</div>

						</div>
					</div>
				</div>

				<div class="site-header__middle container">
					<div class="site-header__logo">
						<a href="index.html">
							<img src="images/logo.png" alt="">
						</a>
					</div>
					<div class="site-header__search">
						<div class="search">
							<form class="search__form" action="">
								<input class="search__input" name="search" placeholder="جستجو از میان 10,000 محصول"
									aria-label="Site search" type="text" autocomplete="off">
								<button class="search__button" type="submit">
									<i class="fa fa-search"></i>
								</button>
								<div class="search__border"></div>
							</form>
						</div>
					</div>
					<div class="site-header__phone">
						<div class="site-header__phone-title">پشتیبانی</div>
						<div class="site-header__phone-number"><span class="ltr_text">0920-150-2830</span></div>
					</div>
				</div>
				<!-- .topbar / end -->
				<div class="site-header__nav-panel">
					<div class="nav-panel">
						<div class="nav-panel__container container">
							<div class="nav-panel__row">
								<div class="nav-panel__logo">
									<a href="index.html">
										<img src="images/shopLogo.png" alt="">
									</a>
								</div>
								<!-- .nav-links -->
								<div class="nav-panel__nav-links nav-links">
									<ul class="nav-links__list">
										<li class="nav-links__item nav-links__item--with-submenu">
											<a href="{% url 'main:home' %}">
												<span><i class="{% url 'main:home' %}"></i>&nbsp; خانه</span>
											</a>
										</li>
										<li class="nav-links__item nav-links__item--with-submenu">
											<a href="{% url 'product:category' None %}">
												<span>
													دسته بندی کالاها
													&nbsp;
													<i class="fa fa-angle-down"></i>
												</span>
											</a>
											<div class="nav-links__megamenu nav-links__megamenu--size--xl">
												<!-- .megamenu -->
												<div class="megamenu">
													<div class="row">
														{% for category in navbar_categories %}
															{% if not category.parent %}
																<div class="col-3">
																	<ul class="megamenu__links megamenu__links--level--0">
																		<li class="megamenu__item megamenu__item--with-submenu">
																			<li class="megamenu__links--level--2">
																				<a href="{{ category.get_absolute_url }}">{{ category.title }}</a>

																			{% if category.children.all %}
																			<ul class="megamenu__links megamenu__links--level--1" style="border-top: 1px solid #e5e5e5;">
																				{% for child in category.children.all %}
																					<li class="megamenu__item">

																						<a href="{{ child.get_absolute_url }}">{{ child.title }}</a>

																						{% if child.children.all %}
																							<ul>
																								{% for second_child in child.children.all %}
																									<li class="megamenu__links--level--2">
																											<a href="{{ second_child.get_absolute_url }}">{{ second_child.title }}</a>
																									</li>
																								{% endfor %}
																							</ul>
																						{% endif %}

																					</li>
																					{% endfor %}
																				</ul>
																			{% endif %}
																		</li>
																	</ul>
																</div>
															{% endif %}
														{% endfor %}
													</div>
												</div>
												<!-- .megamenu / end -->
											</div>
										</li>

										<li class="nav-links__item nav-links__item--with-submenu">
											{% if request.user.is_authenticated %}
											<a href="{% url 'dashboard:dashboard' %}">
												<span>
													<i class="fa fa-user"></i>&nbsp;حساب کاربری
												</span>
											</a>
											{% else %}
											<a href="#">
												<span>
													حساب کاربری&nbsp;<i class="fa fa-angle-down"></i>
												</span>
											</a>
											<div class="nav-links__menu">
												<!-- .menu -->
												<ul class="menu menu--layout--classic">
													<li><a href="{% url 'accounts:login' %}">ورود</a></li>
													<li><a href="{% url 'accounts:register' %}">ثبت نام</a></li>
												</ul>
												<!-- .menu / end -->
											</div>
											{%endif %}
										</li>
										<li class="nav-links__item nav-links__item--with-submenu">
											<a href="{% url 'blog:blog' %}">
												<span><i class="fa fa-newspaper"></i>&nbsp; بلاگ</span>
											</a>
										</li>

									</ul>
								</div>
								<!-- .nav-links / end -->
								<div class="nav-panel__indicators">
									<div class="indicator indicator--trigger--click">
										<button type="button" class="indicator__button">
											<span class="indicator__area">
												<i class="fa fa-plus"></i>
											</span>
										</button>
										<div class="indicator__dropdown">
											<div class="drop-search">
												<form action="" class="drop-search__form">
													<input class="drop-search__input" name="search"
														placeholder="جستجو از میان 10,000 محصول"
														aria-label="Site search" type="text" autocomplete="off">
													<button class="drop-search__button drop-search__button--submit"
														type="submit">
														<i class="fa fa-search"></i>
													</button>
												</form>
											</div>
										</div>
									</div>
									<div class="indicator">
										<a href="wishlist.html" class="indicator__button">
											<span class="indicator__area">
												<i class="fa fa-heart"></i>
												{% if request.user.is_authenticated %}
												<span class="indicator__value" id="wish-list-count">{{ request.user.favorites.all.count }}</span>
												{% else %}
												<span class="indicator__value" id="wish-list-count">0</span>
												{% endif %}
											</span>
										</a>
									</div>
									<div class="indicator">
										<a href="{% url 'product:cart' %}" class="indicator__button">
											<span class="indicator__area">
												<i class="fa fa-shopping-cart"></i>

												<span class="indicator__value" id="cart_count3">{{ cart_count }}</span>
												
											</span>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>

	<!-- desktop site__header / end -->

templates/includes/popular_categories.html
{% load static%}
<div class="block block--highlighted block-categories block-categories--layout--compact">
    <div class="container">
        <div class="block-header">
            <h3 class="block-header__title">دسته های محبوب</h3>
            <div class="block-header__divider"></div>
        </div>

        <div class="block-categories__list">
            {% for category in categories %}
            <div class="block-categories__item category-card category-card--layout--compact">
                <div class="category-card__body">
                    <div class="category-card__image">
                        <a href="">
                            <img src="{{ MEDIA_URL }}{{ category.cover_img }}" alt="">
                        </a>
                    </div>
                    <div class="category-card__content">
                        <div class="category-card__name"><a href="">{{ category.title }}</a></div>
                        <div class="category-card__all"><a href="">نمایش همه</a></div>
                        <div class="category-card__products">{{ category.products_count }} محصول</div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/includes/product_box.html
{% load static %}
{% load lower_price %}
{% load humanize %}

<div class="block-products-carousel__cell">
<div class="product-card" style="width:200px!important; margin-left:12px; margin-bottom:10px">
    <div class="product-card__badges-list">
        {% if type == 'new' %}
            <div class="product-card__badge product-card__badge--sale">جدید</div>
        {% endif %}
    </div>
    <div class="product-card__image">
        <a href="{{ product.get_absolute_url }}" style="display:flex; justify-content:center;">
            <img src="{{ MEDIA_URL }}{{ product.cover_img }}" alt="" style="max-height: 100%; width:auto; ">
        </a>
    </div>
    <div class="product-card__info">
        <div class="product-card__name">
            <a href="{{ product.get_absolute_url }}">
                {{ product.title }}
            </a>
        </div>

    </div>
    <div class="product-card__actions">
        {% if product.available %}
        <div class="product-card__availability">موجودی: 
            <span class="text-success">موجود
            در انبار</span>
        </div>
        <div class="product-card__prices">
            {% with price_item=product|lower_price:"price" %}
                {% if price_item.discount_percent %}
                <span class="product-card__new-price">{{ price_item.real_price|intcomma:False }}
                    تومان</span> 
                    <span class="product-card__old-price">{{ price_item.price|intcomma:False }}
                    تومان</span>
                {% else %}
                <span class="product-card__new-price text-dark">{{ price_item.price|intcomma:False }}
                    تومان</span>
                {% endif %}
            {% endwith %}
            </div>

        {% else %}
            <div class="product-card__availability">موجودی: 
                <span class="text-danger">ناموجود
                    در انبار</span>
                </div>
                <div class="product-card__prices">
                    <span class="text-danger">ناموجود</span>
                </div>

        {% endif %}
        
                    
        <div class="product-card__buttons">
            <button class="btn btn-primary product-card__addtocart" type="button">
                افزودن به سبد
            </button>
            <button
                class="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist"
                type="button">
                <i class="fa fa-heart"></i>
                <span class="fake-svg-icon fake-svg-icon--wishlist-16"></span>
            </button>
            <button
                class="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist"
                type="button">
                <i class="fa fa-shopping-cart"></i>
                <span class="fake-svg-icon fake-svg-icon--wishlist-16"></span>
            </button>
        </div>
    </div>
</div>
</div>

templates/includes/product_slider.html
			<!-- .block-products-carousel -->
			<div class="block block-products-carousel" data-layout="grid-5">
				<div class="container">
					<div class="block-header">
						<h3 class="block-header__title">محصولات ویژه</h3>
						<div class="block-header__divider"></div>
						<ul class="block-header__groups-list">
							<li>
								<button type="button"
									class="block-header__group block-header__group--active">همه</button>
							</li>
                            {% for category in categories%}
							<li>
								<button type="button" class="block-header__group">{{ category.title }}</button>
							</li>
                            {% endfor %}
						</ul>
						<div class="block-header__arrows-list">
							<button class="block-header__arrow block-header__arrow--left" type="button">
								<i class="fas fa-angle-right"></i>
							</button>
							<button class="block-header__arrow block-header__arrow--right" type="button">
								<i class="fas fa-angle-left"></i>
							</button>
						</div>
					</div>
					<div class="block-products-carousel__slider">
						<div class="block-products-carousel__preloader"></div>
						<div class="owl-carousel owl-rtl owl-loaded owl-drag">

							<div class="owl-stage-outer">
								<div class="owl-stage"
									style="transform: translate3d(1120px, 0px, 0px); transition: all 0s ease 0s; width: 4034px; padding-left: 1px; padding-right: 1px;">
                                    
                                    {% for product in products %}
									<div class="owl-item active" style="width: 212px; margin-left: 12px;">
										<div class="block-products-carousel__column">
                                            {% include 'includes/product_box.html' %}
										</div>
									</div>
                                    {% endfor %}

                                </div>
							</div>
							<div class="owl-nav disabled"><button type="button" role="presentation"
									class="owl-prev"><span aria-label="Previous">‹</span></button><button type="button"
									role="presentation" class="owl-next"><span aria-label="Next">›</span></button></div>
							<div class="owl-dots disabled"></div>
						</div>
					</div>
				</div>
			</div>