admin_soft/urls.py
from django.urls import path
from admin_soft import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.index, name='index'),
    path('billing/', views.billing, name='billing'),
    path('tables/', views.tables, name='tables'),
    path('vr/', views.vr, name='vr'),
    path('rtl/', views.rtl, name='rtl'),
    path('profile/', views.profile, name='profile'),

    # Authentication
    path('accounts/login/', views.UserLoginView.as_view(), name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'
    ), name="password_change_done"),
    path('accounts/password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', 
        views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),
]

apps/cart/urls.py
from django.urls import path


app_name = 'cart'
urlpatterns = [
    # path()
]

apps/main/urls.py
from django.urls import path
from .views import (HomeView,
                    ProductSpecialOffersPartial, 
                    BestSellersProductPartial, 
                    PopularCategories,
                    NewestProductsPartial,
                    SliderPartialView,
                    BrandPartialView)


app_name = 'main'
urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('special-offer-products/',ProductSpecialOffersPartial.as_view(), name='product_special_offer_partial'),
    path('best-sellers-products/',BestSellersProductPartial.as_view(), name='best_sellers_product_partial'),
    path('popular-categories/',PopularCategories.as_view(), name='popular_categories_partial'),
    path('newset-products/',NewestProductsPartial.as_view(), name='newset_product_partial'),
    path('slider-partial/', SliderPartialView.as_view(), name='slider_partial'),
    path('brand-partial/', BrandPartialView.as_view(), name='brand_partial'),
]

apps/product/urls.py
from django.urls import path
from .views import (Details, 
    CategoryView, 
    ProductCategoryView,
    RelatedProductsPartial, 
    AddToFavorites,
    RemoveFromFavorites,
    AddCommentView, 
    AddToCartView, 
    CartView,
    RemoveFromCartView,
    CheckoutView)


app_name = 'product'
urlpatterns = [
    path('<int:pk>/<slug:url>/', Details.as_view(), name='details'),
    path('category/<slug:url>/', CategoryView.as_view(), name='category'),
    path('in-category/<slug:url>/', ProductCategoryView.as_view(), name='products_by_category'),
    path('related-products/<int:category_id>/', RelatedProductsPartial.as_view(), name='related_products_partial'),
    path('add-to-favrites/', AddToFavorites.as_view(), name='add_to_favorites'),
    path('remove-from-favorites/', RemoveFromFavorites.as_view(), name='remove_from_favorites'),
    path('add-comment/<int:product_id>/', AddCommentView.as_view(), name='add_comment'),
    path('add-to-cart/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/', RemoveFromCartView.as_view(), name='remove_from_card'),
    path('cart/', CartView.as_view(), name='cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('apps.main.urls', namespace='main')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    path('product/', include('apps.product.urls', namespace='product')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cart/models.py
from django.db import models

# Create your models here.

apps/product/forms.py
from django import forms
from apps.order.models import Order

class AddToCartForm(forms.Form):
    product_id = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'product-id'}))
    price_id = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'price-id'}))
    quantity = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input-number__input form-control form-control-lg', 'id': 'product-quantity', 'min': '1', 'value': '1'}), label='تعداد')


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user', 'order_id', 'created_at', 'tracking_code', 'post_price', 'pay_status', 'status')
        widgets = {
            'receiver_name': forms.TextInput(attrs={'class': 'form-control', 'id':'receiver-name-id', 'placeholder': 'نام و نام خانوادگی'},),
            'receiver_state': forms.TextInput(attrs={'class': 'form-control', 'id':'receiver-state-id', 'placeholder': 'استان'}, ),
            'receiver_city': forms.TextInput(attrs={'class': 'form-control', 'id':'receiver-city-id', 'placeholder': 'شهر'},),
            'receiver_phone_number': forms.TextInput(attrs={'class': 'form-control', 'id':'receiver-phone-number-id', 'placeholder': 'شماره تلفن'}),
            'receiver_address': forms.TextInput(attrs={'class': 'form-control', 'id':'receiver-address-id', 'placeholder': 'آدرس'},),
            'receiver_postal_code': forms.TextInput(attrs={'class': 'form-control', 'id':'receiver-postal-code-id', 'placeholder': 'کد پستی'},),
            'receiver_extra_data': forms.Textarea(attrs={'class': 'form-control w-100', 'rows': '4', 'id':'receiver-extra-data-id', 'placeholder': 'توضیحات'}),
            'pay_method': forms.HiddenInput(attrs={'class': 'form-control', 'id':'pay-method-id', 'placeholder': 'روش پرداخت'},),
        }
        labels = {
            'receiver_name':'نام و نام خانوادگی',
            'receiver_state': 'استان',
            'receiver_city': 'شهر',
            'receiver_phone_number': 'شماره تلفن',
            'receiver_address': 'آدرس',
            'receiver_postal_code': 'کد پستی',
            'receiver_extra_data': 'توضیحات سفارش (اختیاری)',
            'pay_method': 'روش پرداخت',
        }

apps/cart/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from ..product.cart import Cart
from apps.product.models import Product, Price
from apps.product.forms import AddToCartForm


class AddToCartView(View):
    form_class = AddToCartForm

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def get(self,request):
        cart = Cart(request)
        return redirect(self.next)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            product = Product.objects.get(id=kwargs['product_id'])
            price = Price.objects.get(id=kwargs['price_id'])
            cart = Cart(request)
            cart.add(product, price, form.cleaned_data['quantity'])
            if self.next:
                messages.success(request, f'{product.title}&nbsp;به سبد خرید اضافه شد', 'success')
                return redirect(self.next)
            return redirect('dashboard:dashboard')
        messages.warning(request, 'مشکلی در افزودن به سبد خرید رخ داد، دوباره تلاش کنید', 'warning')
        return redirect('dashboard:dashboard')

apps/product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .forms import AddToCartForm
from .models import Product, Category, Price
from django.core.paginator import Paginator
from django.http import HttpResponse
from apps.chat.models import Comment
from apps.chat.forms import CommentForm
from .forms import CheckoutForm
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from .cart import Cart
from django.http import JsonResponse


class Details(View):
    template_name = 'product/details.html'
    form_class = AddToCartForm

    def setup(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, pk=kwargs.get('pk'))
        self.comments = self.product.comments.filter(approved=True).order_by('-publish_date')
        paginator = Paginator(self.comments, 10)
        page_number = request.GET.get('page')
        self.comments_objects = paginator.get_page(page_number)
        self.comment_form = CommentForm
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if not self.product.is_active:
            return redirect('main:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if self.product.prices.exists():
            add_to_cart_form = self.form_class(request.POST or None, initial={'price_id': self.product.prices.all()[0].id,
            'product_id': self.product.id})

            return render(request, self.template_name, {'add_to_cart_form': add_to_cart_form, 'product': self.product,
                                                        'comments': self.comments_objects,
                                                        'comment_form': self.comment_form, 'comments_count': self.comments.count()})

        return render(request, self.template_name, {'product': self.product,
                                                    'comments': self.comments_objects,
                                                    'comment_form': self.comment_form,
                                                    'comments_count': self.comments.count()})

class CategoryView(View):
    template_name = 'product/categories.html'

    def get(self, request, *args, **kwargs):
        if kwargs['url'] != 'None':
            categories = Category.objects.filter(parent__url=kwargs['url'])
        else:
            categories = Category.objects.filter(parent=None)
        return render(request, self.template_name, {'categories': categories})


class ProductCategoryView(View):
    template_name = 'product/products.html'

    def get(self, request, *args, **kwargs):
        category = get_object_or_404(Category, url=kwargs['url'])
        products = Product.objects.filter(category=category).order_by('-available', '-publish_date')
        newest_related_product = Product.objects.filter(category=category).order_by('-available', '-publish_date')[:5]
        paginator = Paginator(products, 25)
        page_number = request.GET.get('page')
        products_objects = paginator.get_page(page_number)
        return render(request, self.template_name, {'category': category, 'products': products_objects, 'newest_related_product': newest_related_product})


class RelatedProductsPartial(View):
    template_name = 'includes/product_slider.html'

    def get(self, request, category_id):
        products = Product.objects.filter(category=category_id)[:25]
        return render(request, self.template_name, {'products': products})


class AddToFavorites(View):
    def get(self, request):
        user = request.user.id
        product = get_object_or_404(Product, id=request.GET['product_id'])
        product.likes.add(user)
        product.save()
        return HttpResponse("Success")


class RemoveFromFavorites(View):
    def get(self, request):
        user = request.user.id
        product = get_object_or_404(Product, id=request.GET['product_id'])
        product.likes.remove(user)
        product.save()
        return HttpResponse("Success")


class AddCommentView(View):
    form_class = CommentForm

    def post(self, request, product_id):
        form = self.form_class(request.POST)
        product_type = ContentType.objects.get(model='product')
        if form.is_valid():
            cleaned_data = form.cleaned_data
            new_comment = Comment.objects.create(
                message=cleaned_data['message'],
                user=request.user,
                content_type=product_type,
                object_id = product_id
            )
            if cleaned_data['reply_to'] != '0':
                reply_to_value = Comment.objects.get(id=cleaned_data['reply_to'])
                new_comment.reply_to = reply_to_value
                new_comment.save()
            return HttpResponse("Success")


class AddToCartView(View):
    form_class = AddToCartForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            cart = Cart(request)
            cart.add(request, cleaned_data['product_id'], cleaned_data['price_id'], cleaned_data['quantity'])
            return JsonResponse({'cart_count': len(cart)})


class CartView(View):

    def get(self, request):
        cart = Cart(request)
        return render(request, 'product/cart.html', {'cart': cart})


class RemoveFromCartView(View):

    def post(self, request):
        cart = Cart(request)
        cart.remove(request, request.POST['product_id'], request.POST['price_id'])
        return HttpResponse('Success')


class CheckoutView(View):
    template_name = 'product/checkout.html'
    form_class = CheckoutForm

    def get(self, request):
        cart = Cart(request)
        return render(request, self.template_name, {'form_checkout': self.form_class, 'cart': cart})

templates/product/cart.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item active" aria-current="page">سبد خرید</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title">
						<h1>سبد خرید</h1></div>
				</div>
			</div>
			<div class="cart block">
				<div class="container">
					<table class="cart__table cart-table">
						<thead class="cart-table__head">
							<tr class="cart-table__row">
								<th class="cart-table__column cart-table__column--image">تصویر</th>
								<th class="cart-table__column cart-table__column--product">محصول</th>
								<th class="cart-table__column cart-table__column--price">قیمت</th>
								<th class="cart-table__column cart-table__column--quantity">تعداد</th>
								<th class="cart-table__column cart-table__column--total">جمع کل</th>
								<th class="cart-table__column cart-table__column--remove"></th>
							</tr>
						</thead>
						<tbody class="cart-table__body">
							{% if not cart.empty %}
								{% for product in cart %}
								<tr class="cart-table__row">
									<td class="cart-table__column cart-table__column--image">
										<a href="{{ product.get_absolute_url }}" target='_blank'><img src="{{ MEDIA_URL }}{{ product.cover_img}}" alt=""></a>
									</td>
									<td class="cart-table__column cart-table__column--product">
										<a href="{{ product.get_absolute_url }}" target='_blank' class="cart-table__product-name">
											{{ product.title }}
										</a>
										{% if product.color %}
										<ul class="cart-table__options">
											<li>رنگ: {{ product.color }}</li>
										</ul>
										{% elif product.attribute %}
										<ul class="cart-table__options">
											<li>ویژگی: {{ product.attribute }}</li>
										</ul>
										{% endif %}
									</td>
									<td class="cart-table__column cart-table__column--price" data-title="قیمت">{{ product.price|intcomma:False }} تومان</td>
									<td class="cart-table__column cart-table__column--quantity" data-title="تعداد">
									<input type="hidden" id="price-id" value="{{ product.price_id }}" data-count="{{ product.stock_count}} "></input>
										<div class="input-number">
											<input class="form-control input-number__input" id="product-quantity" type="number" min="1" value="{{ product.quantity }}">
											<div class="input-number__add" data-productquantity=""></div>
											<div class="input-number__sub"></div>
										</div>
									</td>
                                        <td class="cart-table__column cart-table__column--total" data-title="جمع کل">{{ product.total|intcomma:False }} تومان</td>
									<td class="cart-table__column cart-table__column--remove">
										<button type="button" class="btn btn-light btn-sm btn-svg-icon remove-from-cart" data-productid="{{ product.product_id }}" data-priceid="{{ product.price_id }}">
											<i class="fa fa-trash"></i>
										</button>
									</td>
								</tr>
								{% endfor %}
							{% else %}
							<tr>
								<td colspan="6" class="bg-warning text-center p-2">
									 محصولی در سبد خرید شما موجود نیست
								</td>
								</tr>
							{% endif%}
						</tbody>
					</table>
					<div class="cart__actions">
						<form class="cart__coupon-form">
							<label for="input-coupon-code" class="sr-only">رمز عبور</label>
							<input type="text" class="form-control" id="input-coupon-code" placeholder="کد تخفیف">
							<button type="submit" class="btn btn-primary">اعمال کد تخفیف</button>
						</form>
						<div class="cart__buttons"><a href="index.html" class="btn btn-light">ادامه خرید</a> <a href="" class="btn btn-primary cart__update-button">به روز رسانی سبد</a></div>
					</div>
					<div class="row justify-content-end pt-5">
						<div class="col-12 col-md-7 col-lg-6 col-xl-5">
							<div class="card">
								<div class="card-body">
									<h3 class="card-title">مجموع سبد</h3>
									<table class="cart__totals">
										<thead class="cart__totals-header">
											{% if cart %}
											<tr>
												<th>جمع جزء</th>
												<td>{{ cart.total_price|intcomma:False }} تومان</td>
											</tr>
											{% endif %}
										</thead>
										<tbody class="cart__totals-body">
											<tr>
												<th>حمل و نقل</th>
												<td>25,000 تومان
													<div class="cart__calc-shipping"><a href="#">محاسبه هزینه</a></div>
												</td>
											</tr>
											<tr>
												<th>مالیات</th>
												<td>0 تومان</td>
											</tr>
										</tbody>
										<tfoot class="cart__totals-footer">
											<tr>
												<th> جمع کل: {{ cart.total_price|intcomma:False }}</th>
												<td> تومان</td>
											</tr>
										</tfoot>
									</table><a class="btn btn-primary btn-xl btn-block cart__checkout-button" href="{% url 'product:checkout' %}">پرداخت</a></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->
{% endblock %}

{% block script %}
<script>
	$('.input-number__add').click(function(){
		var product_quantity = document.getElementById('product-quantity')
		var price_max_count = document.getElementById('price-id')
	
		if (product_quantity.value < price_max_count.dataset.count ){
			product_quantity.value = Number(product_quantity.value) + 1
	
		}
	});
	
	$('.input-number__sub').click(function(){
		var product_quantity = document.getElementById('product-quantity')
		if (product_quantity.value!=1){
			product_quantity.value = Number(product_quantity.value) - 1
		}
	});

	$('.remove-from-cart').click(function(){
		var product_id = $(this).attr('data-productid');
		var price_id = $(this).attr('data-priceid');
	
		$.ajax(
		{
			type:"POST",
			url: "{% url 'product:remove_from_card' %}",
			
			data:{
				product_id: product_id,
				price_id: price_id,
				csrfmiddlewaretoken: '{{ csrf_token }}',
				dataType: "json",
			},
			success: function(data){

			}
		})

	});
</script>
{% endblock %}

templates/product/categories.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="{% url 'main:home' %}">خانه</a>
									/
								</li>
								<li class="breadcrumb-item active" aria-current="page">دسته بندی محصولات</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title">
						<h1>دسته بندی محصولات</h1>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="block">
							<div class="block block--highlighted block-categories block-categories--layout--compact">
								<div class="container">
									<div class="block-categories__list">
										{% for category in categories %}
											<div class="block-categories__item category-card category-card--layout--compact">
												<div class="category-card__body">
													<div class="category-card__image">
														<a href="">
															<img src="{{ MEDIA_URL }}{{ category.cover_img }}" alt="">
														</a>
													</div>
													<div class="category-card__content">
														<div class="category-card__name">
															{% if category.children.all %}
																<a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
															{% else %}
																<a href="{{ category.get_product_url }}">{{ category.title }}</a>
															{% endif %}
														</div>
														<div class="category-card__all"><a href="">نمایش همه</a></div>
														<div class="category-card__products">{{ category.products.all.count }}&nbsp;محصول</div>
													</div>
												</div>
											</div>
										{% endfor %}
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->
{% endblock %}

templates/product/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content%}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								
								<li class="breadcrumb-item active" aria-current="page">پرداخت</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title">
						<h1>پرداخت</h1></div>
				</div>
			</div>
			<div class="checkout block">
				<div class="container">
					<div class="row">
						{% if not request.user.is_authenticated %}
						<div class="col-12 mb-3">
							<div class="alert alert-lg alert-primary">حساب کاربری دارید؟ 
								<a href="{% url 'accounts:login' %}">وارد حساب خود شوید</a>،
								حساب ندارید؟
								<a href="{% url 'accounts:register' %}">ساخت حساب کاربری</a></div>
						</div>
						{% endif %}
						<div class="col-12 col-lg-6 col-xl-7">
							<div class="card mb-lg-0">
								<div class="card-body">
									<h3 class="card-title">جزئیات پرداخت</h3>
									<div class="form-group">
										<label for="{{ form_checkout.receiver_phone_number.field.widget.attrs.id }}">{{ form_checkout.receiver_phone_number.label }}</label>
										{{ form_checkout.receiver_phone_number }}
									</div>
									<div class="form-group">
										<label for="{{ form_checkout.receiver_name.field.widget.attrs.id }}">{{ form_checkout.receiver_name.label }}</label>
										{{ form_checkout.receiver_name }}
									</div>
									<div class="form-group">
										<label for="{{ form_checkout.receiver_state.field.widget.attrs.id }}">{{ form_checkout.receiver_state.label }}</label>
										{{ form_checkout.receiver_state }}
									</div>
									<div class="form-group">
										<label for="{{ form_checkout.receiver_city.field.widget.attrs.id }}">{{ form_checkout.receiver_city.label }}</label>
										{{ form_checkout.receiver_city }}
									</div>
									<div class="form-group">
										<label for="{{ form_checkout.receiver_postal_code.field.widget.attrs.id }}">{{ form_checkout.receiver_postal_code.label }}</label>
										{{ form_checkout.receiver_postal_code }}
									</div>
									<div class="form-group">
										<label for="{{ form_checkout.receiver_address.field.widget.attrs.id }}">{{ form_checkout.receiver_address.label }}</label>
										{{ form_checkout.receiver_address }}
									</div>
								</div>
								<div class="card-divider"></div>
								<div class="card-body">
									<h3 class="card-title">جزئیات حمل و نقل</h3>
									<div class="form-group">
										<div class="form-group">
											{{ form_checkout.pay_method }}
											<label for="{{ form_checkout.receiver_extra_data.field.widget.attrs.id }}">{{ form_checkout.receiver_extra_data.label }}</label>
											{{ form_checkout.receiver_extra_data }}
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-12 col-lg-6 col-xl-5 mt-4 mt-lg-0">
							<div class="card mb-0">
								<div class="card-body">
									<h3 class="card-title">سفارش شما</h3>
									<table class="checkout__totals">
										<thead class="checkout__totals-header">
											<tr>
												<th>محصول</th>
												<th>جمع کل</th>
											</tr>
										</thead>
										<tbody class="checkout__totals-products">
                                            {% for product in cart %}
                                                <tr>
                                                    <td>{{ product.title }} <span class="d-inline-block">× {{ product.quantity }}</span></td>
                                                    <td>{{ product.total|intcomma:False }} تومان</td>
                                                </tr>
                                            {% endfor %}
										</tbody>
										<tbody class="checkout__totals-subtotals">
											<tr>
												<th>جمع جزء</th>
												<td>{{ cart.total_price|intcomma:False }} تومان</td>
											</tr>
											<tr>
												<th>حمل و نقل</th>
												<td> 222 تومان</td>
											</tr>
										</tbody>
										<tfoot class="checkout__totals-footer">
											<tr>
												<th>جمع کل</th>
												<td>{{ cart.total_price|intcomma:False }} تومان</td>
											</tr>
										</tfoot>
									</table>
									<div class="payment-methods">
										<ul class="payment-methods__list">
											<li class="payment-methods__item">
												<label class="payment-methods__item-header"><span class="payment-methods__item-radio input-radio"><span class="input-radio__body"><input class="input-radio__input" name="checkout_payment_method" type="radio"> <span class="input-radio__circle"></span> </span>
													</span><span class="payment-methods__item-title">پرداخت آنلاین</span></label>
												<div class="payment-methods__item-container">
													<div class="payment-methods__item-description text-muted">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک</div>
												</div>
											</li>
											{% comment %} <li class="payment-methods__item">
												<label class="payment-methods__item-header"><span class="payment-methods__item-radio input-radio"><span class="input-radio__body"><input class="input-radio__input" name="checkout_payment_method" type="radio"> <span class="input-radio__circle"></span> </span>
													</span><span class="payment-methods__item-title">پرداخت در محل</span>
												</label>
												<div class="payment-methods__item-container">
													<div class="payment-methods__item-description text-muted">لورم ایپسوم متن ساختگی با تولید</div>
												</div>
											</li> {% endcomment %}
										</ul>
									</div>
									<div class="checkout__agree form-group">
										<div class="form-check"><span class="form-check-input input-check"><span class="input-check__body"><input class="input-check__input" type="checkbox" id="checkout-terms"> <span class="input-check__box"></span>
											<svg class="input-check__icon" width="9px" height="7px">
												<use xlink:href="images/sprite.svg#check-9x7"></use>
											</svg>
											</span>
											</span>
											<label class="form-check-label" for="checkout-terms">من <a target="_blank" href="terms-and-conditions.html">قوانین و مقررات</a> را خوانده و موافقم *</label>
										</div>
									</div>
									<button type="submit" class="btn btn-primary btn-xl btn-block">ثبت سفارش</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->
{% endblock %}