admin_soft/urls.py
from django.urls import path
from admin_soft import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.index, name='index'),
    path('billing/', views.billing, name='billing'),
    path('tables/', views.tables, name='tables'),
    path('vr/', views.vr, name='vr'),
    path('rtl/', views.rtl, name='rtl'),
    path('profile/', views.profile, name='profile'),

    # Authentication
    path('accounts/login/', views.UserLoginView.as_view(), name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'
    ), name="password_change_done"),
    path('accounts/password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', 
        views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),
]

apps/dashboard/urls.py
from django.urls import path
from .views import (DashboardView,
                    ProfileView,
                    PasswordChangeView,
                    SuccessPasswordChangeView,
                    AddressesView,
                    AddAddressView,
                    EditAddressView,
                    DeleteAddressView,
                    OrdersView,
                    OrderView,
                    ReturnedOrdersView,
                    ReturnedOrderView,
                    AddReturnedOrderView,
                    EditReturnedOrderView)


app_name = 'dashboard'
urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('change-password/', PasswordChangeView.as_view(), name='password_change'),
    path('success-change-password/', SuccessPasswordChangeView.as_view(), name='success_change_password'),
    path('addresses/', AddressesView.as_view(), name='addresses'),
    path('add-new-address/', AddAddressView.as_view(), name='add_address'),
    path('edit-address/<int:pk>/', EditAddressView.as_view(), name='edit_address'),
    path('delete-address/<int:pk>/', DeleteAddressView.as_view(), name='delete_address'),
    path('orders/', OrdersView.as_view(), name='orders'),
    path('order/<int:id>/', OrderView.as_view(), name='order'),
    path('returned-orders/', ReturnedOrdersView.as_view(), name='returned_orders'),
    path('returned-order/<int:order_code>/', ReturnedOrderView.as_view(), name='returned_order'),
    path('add-returned-order/<int:order_id>/', AddReturnedOrderView.as_view(), name='add_returned_order'),
    path('edit-returned-order/<int:order_id>/', EditReturnedOrderView.as_view(), name='edit_returned_order'),
]

apps/main/urls.py
from django.urls import path
from .views import (HomeView,
                    ProductSpecialOffersPartial, 
                    BestSellersProductPartial, 
                    PopularCategories,
                    NewestProductsPartial,
                    SliderPartialView,
                    BrandPartialView)


app_name = 'main'
urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('special-offer-products/',ProductSpecialOffersPartial.as_view(), name='product_special_offer_partial'),
    path('best-sellers-products/',BestSellersProductPartial.as_view(), name='best_sellers_product_partial'),
    path('popular-categories/',PopularCategories.as_view(), name='popular_categories_partial'),
    path('newset-products/',NewestProductsPartial.as_view(), name='newset_product_partial'),
    path('slider-partial/', SliderPartialView.as_view(), name='slider_partial'),
    path('brand-partial/', BrandPartialView.as_view(), name='brand_partial'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('apps.main.urls', namespace='main')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    path('product/', include('apps.product.urls', namespace='product')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/order/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from apps.product.models import Product, Price
import random


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='orders', on_delete=models.CASCADE, verbose_name='کاربر')
    order_id = models.CharField(max_length=8, default=random.randint(10000000, 99999999), unique=True, verbose_name='شماره سفارش')
    created_at = models.DateTimeField(auto_created=True, verbose_name='سفارش داده شده در تاریخ')
    STATUS_LIST = [
        ('در حال پردازش', 'در حال پردازش'),
        ('ارسال شده', 'ارسال شده'),
        ('تحویل مرسوله به مشتری', 'تحویل مرسوله به مشتری'),
        ('لغو شده', 'لغو شده'),
        ('مرجوع شده', 'مرجوع شده'),
    ]
    tracking_code = models.CharField(max_length=30, null=True, blank=True, verbose_name='کد رهگیری پستی')
    receiver_name = models.CharField(max_length=100, verbose_name='نام گیرنده')
    receiver_phone_number = models.CharField(max_length=11, verbose_name='شماره تلفن گیرنده')
    receiver_state = models.CharField(max_length=15, verbose_name='استان گیرنده')
    receiver_city = models.CharField(max_length=15, verbose_name='شهر گیرنده')
    receiver_address = models.CharField(max_length=650, verbose_name='آدرس گیرنده')
    receiver_postal_code = models.CharField(max_length=18, verbose_name='کدپستی  گیرنده')
    receiver_extra_data = models.CharField(max_length=350, blank=True, null=True, verbose_name='توضیحات اضافه')
    post_price = models.IntegerField(blank=True, null=True, verbose_name='هزینه پست')
    pay_method = models.CharField(max_length=15, default='online', blank=True, null=True, verbose_name='روش پرداخت')
    PAY_STATUS = [
        ('N', 'در انتظار پرداخت'),
        ('Y', 'پرداخت شده'),
    ]
    pay_status = models.CharField(max_length=35, choices=PAY_STATUS, default=PAY_STATUS[0], verbose_name='وضعیت پرداخت')
    status = models.CharField(max_length=40, choices=STATUS_LIST, default=STATUS_LIST[0][0], verbose_name='وضعیت')

    def total_price(self):
        count = 0
        for product in self.order_items.all():
            count += product.price.price * product.quantity
        return str(count)

    def __str__(self):
        return f'{self.order_id} - {self.status} - {self.created_at}'

    def get_absolute_url(self):
        return reverse('dashboard:order', args=(self.id,))

    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارشات'


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items', verbose_name='سفارش')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, verbose_name='محصول')
    price = models.ForeignKey(Price, on_delete=models.SET_NULL, null=True, verbose_name='قیمت')
    quantity = models.IntegerField(null=True, default=1, verbose_name='تعداد')
    filled_price = models.CharField(max_length=12, blank=True, null=True, verbose_name='قیمت خریداری شده')
    discount = models.CharField(max_length=500, blank=True, null=True, verbose_name='میزان تخفیف')

    def get_absolute_url(self):
        return reverse('product:details', args=(self.product.id, self.product.slug))

    def __str__(self):
        return f'{self.product.title} - {self.filled_price}'

    class Meta:
        verbose_name = 'محصول سفارش داده شده'
        verbose_name_plural = 'محصولات سفارش داده شده'


class ReturnOrder(models.Model):
    return_order_id = models.CharField(max_length=8, default=random.randint(10000000, 99999999), unique=True,
                                       verbose_name='شماره سفارش مرجوعی')
    products = models.ManyToManyField(OrderProduct, related_name='returned_items', verbose_name='محصول')
    order = models.ForeignKey(Order, related_name='returns', on_delete=models.SET_NULL, null=True, verbose_name='سفارش')
    description = models.CharField(max_length=555, blank=True, null=True, verbose_name='توضیح')
    created_at = models.DateTimeField(auto_created=True, verbose_name='ساخته شده در')

    def total_price(self):
        count = 0
        for product in self.products.all():
            count += product.price.price * product.quantity
        return str(count)

    def get_absolute_url(self):
        return reverse('dashboard:returned_order', args=(self.return_order_id,))

    def __iter__(self):
        for item in self.__dict__:
            yield item

    def __str__(self):
        return f'{self.return_order_id} - {self.created_at}'

    class Meta:
        verbose_name = 'سفارش مرجوعی'
        verbose_name_plural = 'سفارشات مرجوعی'

admin_soft/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, UsernameField, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class RegistrationForm(UserCreationForm):
  password1 = forms.CharField(
      label=_("Password"),
      widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
  )
  password2 = forms.CharField(
      label=_("Password Confirmation"),
      widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password Confirmation'}),
  )

  class Meta:
    model = User
    fields = ('username', 'email', )

    widgets = {
      'username': forms.TextInput(attrs={
          'class': 'form-control',
          'placeholder': 'Username'
      }),
      'email': forms.EmailInput(attrs={
          'class': 'form-control',
          'placeholder': 'Email'
      })
    }


class LoginForm(AuthenticationForm):
  username = UsernameField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Username"}))
  password = forms.CharField(
      label=_("Password"),
      strip=False,
      widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}),
  )

class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control'
    }))

class UserSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'New Password'
    }), label="New Password")
    new_password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Confirm New Password'
    }), label="Confirm New Password")
    

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Old Password'
    }), label='Old Password')
    new_password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'New Password'
    }), label="New Password")
    new_password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Confirm New Password'
    }), label="Confirm New Password")

apps/dashboard/forms.py
from cProfile import label

from django import forms
from django.contrib.auth.forms import PasswordChangeForm as BasePasswordChangeForm
from apps.accounts.models import User, Address
from apps.order.models import ReturnOrder, Order, OrderProduct


class ProfileForm(forms.ModelForm):
    phone_number = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'شماره تلفن خود را وارد کنید', 'readonly': ''}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'نام خود را وارد کنید'}),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'نام خانوادگی خود را وارد کنید'}),
            'email': forms.EmailInput(
                attrs={'class': 'form-control', 'placeholder': 'ایمیل شما'}),
        }


class PasswordChangeForm(BasePasswordChangeForm):
    error_messages = {
        'password_mismatch': ('رمز عبور جدید با تکرار آن مطابقت ندارد'),
        'password_incorrect': ("رمز عبور فعلی درست وارد نشده"),
    }
    old_password = forms.CharField(
        label='رمز عبور فعلی',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password',
                                          'autofocus': True,
                                          'class': 'form-control'}),
    )
    new_password1 = forms.CharField(
        label="رمزعبور جدید",
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control'}),
        strip=False,
    )
    new_password2 = forms.CharField(
        label="تایید رمز عبور جدید",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control'}),
    )


class AddAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ('user', )
        widgets = {
            'receiver_name': forms.TextInput(attrs={'class': 'form-control'}),
            'receiver_phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control'}),
        }


class AddReturnedOrderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop('order_id', None)
        super(AddReturnedOrderForm, self).__init__(*args, **kwargs)
        self.fields['products'].queryset = OrderProduct.objects.filter(order=self.order)


    class Meta:
        model = ReturnOrder
        fields = ['products', 'description']
        widgets = {
            'products': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control',
                                                                   'style': 'height:100px!important'}),
        }

apps/order/forms.py
from django import forms
from .models import Order, ReturnOrder


class OrderForm(forms.ModelForm):
    receiver_extra_data = forms.CharField(
        widget=forms.Textarea(attrs={'cols': '40', 'rows': '3'}), label='توضیحات اضافه')
    post_price = forms.IntegerField(
        widget=forms.NumberInput(attrs={'style': 'width:min(100%, 700px)'}), label='هزینه پست')

    class Meta:
        model = Order
        fields = '__all__'


class ReturnOrderForm(forms.ModelForm):
    description = forms.CharField(
        widget=forms.Textarea(attrs={'cols': '40', 'rows': '3'}), label='توضیحات')

    class Meta:
        model = ReturnOrder
        fields = '__all__'

apps/order/views.py
from django.shortcuts import render

# Create your views here.

templates/dashboard/add_address.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="{% url 'main:home' %}">خانه</a>
									/
								</li>
								<li class="breadcrumb-item"><a href="">داشبورد</a>

								</li>

							</ol>
						</nav>
					</div>
					<div class="page-header__title">
						<h1>حساب کاربری</h1></div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row">
						<div class="col-12 col-lg-3 d-flex">
							<div class="account-nav flex-grow-1">
								<h4 class="account-nav__title">ناوبری</h4>
								<ul>
									<li class="account-nav__item"><a href="{% url 'dashboard:dashboard' %}">داشبورد</a></li>
									<li class="account-nav__item"><a href="{% url 'dashboard:profile' %}">ویرایش پروفایل</a></li>
									<li class="account-nav__item account-nav__item--active"><a href="{% url 'dashboard:addresses' %}">آدرس های شما</a></li>
									<li class="account-nav__item"><a href="{% url 'dashboard:orders' %}">سفارشات شما</a></li>
									<li class="account-nav__item"><a href="{% url 'dashboard:returned_orders' %}">سفارشات مرجوعی</a></li>
									<li class="account-nav__item"><a href="{% url 'dashboard:password_change' %}">تغییر رمز عبور</a></li>
									<li class="account-nav__item"><a href="{% url 'accounts:logout' %}">خروج</a></li>
								</ul>
							</div>
						</div>
						<div class="col-12 col-lg-9 mt-4 mt-lg-0">
							<div class="card">
								<div class="card-header">
									<h5>(افزودن / ویرایش) آدرس</h5></div>
								<div class="card-divider"></div>
								<div class="card-body">
									<div class="row no-gutters">
										<div class="col-12 col-lg-7 col-xl-6">
											<form method="post">
												{% csrf_token %}
												<div class="form-group">
													<label for="id_old_password">نام گیرنده</label>
													 {{ form.receiver_name }}
													 <p class="text-danger">{{ form.receiver_name.errors.0 }}</p>
												</div>
												<div class="form-group">
													<label for="id_new_password1">شماره تماس گیرنده</label>
													{{ form.receiver_phone_number }}
													<p class="text-danger">{{ form.receiver_phone_number.errors.0 }}</p>
												</div>
												<div class="form-group">
													<label for="id_new_password2">استان</label>
													{{ form.state }}
													<p class="text-danger">{{ form.state.errors.0 }}</p>
												</div>
												<div class="form-group">
													<label for="id_new_password2">شهر</label>
													{{ form.city }}
													<p class="text-danger">{{ form.city.errors.0 }}</p>
												</div>
												<div class="form-group">
													<label for="id_new_password2">کد پستی</label>
													{{ form.postal_code }}
													<p class="text-danger">{{ form.postal_code.errors.0 }}</p>
												</div>
												<div class="form-group">
													<label for="id_new_password2">آدرس</label>
													{{ form.address }}
													<p class="text-danger">{{ form.address.errors.0 }}</p>
												</div>
												<div class="form-group mt-5 mb-0">
													<button class="btn btn-primary">تغییر</button>
												</div>
											</form>
										</div>
									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
								<!-- site__body / end -->
{% endblock %}

templates/dashboard/add_returned_order.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="{% url 'main:home' %}">خانه</a>
									/
								</li>
								<li class="breadcrumb-item"><a href="">داشبورد</a>

								</li>

							</ol>
						</nav>
					</div>
					<div class="page-header__title">
						<h1>حساب کاربری</h1></div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row">
						<div class="col-12 col-lg-3 d-flex">
							<div class="account-nav flex-grow-1">
								<h4 class="account-nav__title">ناوبری</h4>
								<ul>
									<li class="account-nav__item"><a href="{% url 'dashboard:dashboard' %}">داشبورد</a></li>
									<li class="account-nav__item"><a href="{% url 'dashboard:profile' %}">ویرایش پروفایل</a></li>
									<li class="account-nav__item"><a href="{% url 'dashboard:addresses' %}">آدرس های شما</a></li>
									<li class="account-nav__item"><a href="{% url 'dashboard:orders' %}">سفارشات شما</a></li>
									<li class="account-nav__item account-nav__item--active"><a href="{% url 'dashboard:returned_orders' %}">سفارشات مرجوعی</a></li>
									<li class="account-nav__item"><a href="{% url 'dashboard:password_change' %}">تغییر رمز عبور</a></li>
									<li class="account-nav__item"><a href="{% url 'accounts:logout' %}">خروج</a></li>
								</ul>
							</div>
						</div>
						<div class="col-12 col-lg-9 mt-4 mt-lg-0">
							<div class="card">
								<div class="card-header">
									<h5>ثبت مرجوعی</h5></div>
								<div class="card-divider"></div>
								<div class="card-body">
									<div class="row no-gutters">
										<div class="col-12">
											<form method="post">
												{% csrf_token %}
												<div class="form-group">
													<label for="id_new_password1">{{ form.products.label }}</label>
													{{ form.products }}
													<p class="text-danger">{{ form.products.errors.0 }}</p>
												</div>
												<div class="form-group">
													<label for="id_new_password2">{{ form.description.label }}</label>
													{{ form.description }}
													<p class="text-danger">{{ form.description.errors.0 }}</p>
												</div>
												<div class="form-group mt-5 mb-0 ">
													<button class="btn btn-primary col-3 float-right">ثبت</button>
												</div>
											</form>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
						
		<!-- site__body / end -->
{% endblock %}

templates/dashboard/addresses.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="site__body">
	<div class="page-header">
		<div class="page-header__container container">
			<div class="page-header__breadcrumb">
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="{% url 'main:home' %}">خانه</a>
							/
						</li>
						<li class="breadcrumb-item"><a href="">داشبورد</a>

						</li>

					</ol>
				</nav>
			</div>
			<div class="page-header__title">
				<h1>حساب کاربری</h1></div>
		</div>
	</div>
	<div class="block">
		<div class="container">
			<div class="row">
				<div class="col-12 col-lg-3 d-flex">
					<div class="account-nav flex-grow-1">
						<h4 class="account-nav__title">ناوبری</h4>
						<ul>
							<li class="account-nav__item"><a href="{% url 'dashboard:dashboard' %}">داشبورد</a></li>
							<li class="account-nav__item"><a href="{% url 'dashboard:profile' %}">ویرایش پروفایل</a></li>
							<li class="account-nav__item account-nav__item--active"><a href="{% url 'dashboard:addresses' %}">آدرس های شما</a></li>
							<li class="account-nav__item"><a href="{% url 'dashboard:orders' %}">سفارشات شما</a></li>
							<li class="account-nav__item"><a href="{% url 'dashboard:returned_orders' %}">سفارشات مرجوعی</a></li>
							<li class="account-nav__item"><a href="{% url 'dashboard:password_change' %}">تغییر رمز عبور</a></li>
							<li class="account-nav__item"><a href="{% url 'accounts:logout' %}">خروج</a></li>
						</ul>
					</div>
				</div>
				<div class="col-12 col-lg-9 mt-4 mt-lg-0">
					<div class="dashboard">
						<div class="dashboard__orders card">
							<div class="card-header row">
								<h5 class="d-inline-block">آدرس های شما</h5>
								<div class="topbar__spring"></div>
								<a href="{% url 'dashboard:add_address' %}" class="btn btn-dark">افزودن آدرس جدید</a>
							</div>
							<div class="card-divider"></div>
							<div class="card-table">
								<div class="table-responsive-sm">
									<table>
										<thead>
											<tr class="text-center">
												<th>نام گیرنده</th>
												<th>شماره تلفن</th>
												<th>استان</th>
												<th>شهر</th>
												<th>ویرایش</th>
												<th>حذف</th>
											</tr>
										</thead>
										<tbody>
											<tr class="text-center">
											{% if request.user.addresses.all %}
												{% for address in request.user.addresses.all %}
														<td><a href="{{ address.get_absolute_url }}">{{ address.receiver_name }}</a></td>
														<td>{{ address.receiver_phone_number }}</td>
														<td>{{ address.state }}</td>
														<td>{{ address.city }}</td>
														<td><a href="{{ address.get_absolute_url }}" class="btn btn-secondary">ویرایش یا نمایش</a></td>
														<td><a href="{% url 'dashboard:delete_address' address.id %}" class="btn btn-primary w-100">حذف</a></td>
												{% endfor %}
											{% else %}
												<td colspan="6" class="bg-warning text-center">موردی یافت نشد</td>
											{% endif %}
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/dashboard/password_change.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="{% url 'main:home' %}">خانه</a>
									/
								</li>
								<li class="breadcrumb-item"><a href="">داشبورد</a>

								</li>

							</ol>
						</nav>
					</div>
					<div class="page-header__title">
						<h1>حساب کاربری</h1></div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row">
						<div class="col-12 col-lg-3 d-flex">
							<div class="account-nav flex-grow-1">
								<h4 class="account-nav__title">ناوبری</h4>
								<ul>
									<li class="account-nav__item"><a href="{% url 'dashboard:dashboard' %}">داشبورد</a></li>
									<li class="account-nav__item"><a href="{% url 'dashboard:profile' %}">ویرایش پروفایل</a></li>
									<li class="account-nav__item"><a href="{% url 'dashboard:addresses' %}">آدرس های شما</a></li>
									<li class="account-nav__item"><a href="{% url 'dashboard:orders' %}">سفارشات شما</a></li>
									<li class="account-nav__item"><a href="{% url 'dashboard:returned_orders' %}">سفارشات مرجوعی</a></li>
									<li class="account-nav__item account-nav__item--active"><a href="{% url 'dashboard:password_change' %}">تغییر رمز عبور</a></li>
									<li class="account-nav__item"><a href="{% url 'accounts:logout' %}">خروج</a></li>
								</ul>
							</div>
						</div>
						<div class="col-12 col-lg-9 mt-4 mt-lg-0">
							<div class="card">
								<div class="card-header">
									<h5>تغییر رمز عبور</h5></div>
								<div class="card-divider"></div>
								<div class="card-body">
									<div class="row no-gutters">
										<div class="col-12 col-lg-7 col-xl-6">
											<form method="post">
												{% csrf_token %}
												<div class="form-group">
													<label for="id_old_password">رمز عبور کنونی</label>
													 {{ form.old_password }}
													 <p class="text-danger">{{ form.old_password.errors.0 }}</p>
												</div>
												<div class="form-group">
													<label for="id_new_password1">رمز عبور جدید</label>
													{{ form.new_password1 }}
													<p class="text-danger">{{ form.new_password1.errors.0 }}</p>
												</div>
												<div class="form-group">
													<label for="id_new_password2">تکرار رمز عبور جدید</label>
													{{ form.new_password2 }}
													<p class="text-danger">{{ form.new_password2.errors.0 }}</p>
												</div>
												<div class="form-group mt-5 mb-0">
													<button class="btn btn-primary">تغییر</button>
												</div>
											</form>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->
{% endblock %}